dot:
	dot -Tpng a.dot -o a.png
	dot -Tpng s0.dot -o s0.png
	dot -Tpng s1.dot -o s1.png
	dot -Tpng s2.dot -o s2.png
	dot -Tpng s3.dot -o s3.png
	dot -Tpng s4.dot -o s4.png
	dot -Tpng s5.dot -o s5.png
	dot -Tpng s6.dot -o s6.png
	dot -Tpng s7.dot -o s7.png
	firefox s0.png
	firefox s1.png
	firefox s2.png
	firefox s3.png
	firefox s4.png
	firefox s5.png
	firefox s6.png
	firefox s7.png

